### ISSUE TITLE
起動時にpidファイルを作成するように

### ISSUE THREAD

**Issue by kkitai** [cappyzawa/terraform-registry#1]
プロセス監視などを行いたいので、/var/run/regsitry.pidファイルなどにpidファイルを作成するような仕組みが欲しいです。
また、--pidオプションとかでpidファイルのパスも変えられると嬉しいです。

**Comment by cappyzawa** [comment]
This issue is fixed by https://github.com/cappyzawa/terraform-registry/pull/2.

You can use env: `PID_FILE` for building this server.

**Comment by cappyzawa** [comment]
https://github.com/cappyzawa/terraform-registry/releases/tag/v0.1.0

**Comment by kkitai** [comment]
thank you for quick help
